[package]
name = "frontier-address-converter"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
hex = "0.4"
sp-core = "37"
tracing = "0.1"
tracing-subscriber = "0.3"
